name 'workflow'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures workflow'
long_description 'Installs/Configures workflow'
version '0.1.0'
