name 'learn-the-basics-windows'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures learn-the-basics-windows'
long_description 'Installs/Configures learn-the-basics-windows'
version '0.1.0'

depends 'workflow'
depends 'windows', '~> 1.39.1'
